--SELECT * FROM REGISTRATION_TIME
--INNER JOIN REGISTRATION_DATE ON REGISTRATION_TIME.TimeID= REGISTRATION_DATE.TimeID
--INNER JOIN REGISTRATION ON REGISTRATION_DATE.DateID = REGISTRATION.DateID
--INNER JOIN DOCTOR_SERVICE ON REGISTRATION.DoctorServiceID = DOCTOR_SERVICE.DoctorServiceID
--WHERE REGISTRATION_DATE.Date='2022-05-22' AND DOCTOR_SERVICE.DoctorID = 2
--AND DOCTOR_SERVICE.ServiceID = 3


SELECT * FROM REGISTRATION_DATE
INNER JOIN REGISTRATION ON REGISTRATION.DateID = REGISTRATION_DATE.DateID
INNER JOIN DOCTOR_SERVICE ON REGISTRATION.DoctorServiceID = DOCTOR_SERVICE.DoctorServiceID
WHERE REGISTRATION_DATE.Date='2022-05-22' AND REGISTRATION_DATE.TimeID='14:00' 

AND DOCTOR_SERVICE.ServiceID = 3