USE [CLINICS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DOCTOR_RATING](
	[CommentID] [int] NOT NULL identity(1,1),
	[DoctorID] [int] NOT NULL,
	[ClientID] [int] NOT NULL,
	[Rating] [float] NOT NULL,
	[Comment] [nvarchar](1000) NULL,
 CONSTRAINT [PK_DOCTOR_RATING] PRIMARY KEY CLUSTERED 
(
	[CommentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[DOCTOR_RATING]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_RATING_CLIENT] FOREIGN KEY([ClientID])
REFERENCES [dbo].[CLIENT] ([ClientID])
GO

ALTER TABLE [dbo].[DOCTOR_RATING] CHECK CONSTRAINT [FK_DOCTOR_RATING_CLIENT]
GO

ALTER TABLE [dbo].[DOCTOR_RATING]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_RATING_DOCTOR] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[DOCTOR] ([DoctorID])
GO

ALTER TABLE [dbo].[DOCTOR_RATING] CHECK CONSTRAINT [FK_DOCTOR_RATING_DOCTOR]
GO


