USE [CLINICS]
GO

/****** Object:  Table [dbo].[DOCTOR_SERVICE]    Script Date: 14.05.2022 19:12:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DOCTOR_SERVICE](
	[DoctorServiceID] [int] NOT NULL identity(1,1),
	[DoctorID] [int] NOT NULL,
	[ServiceID] [int] NOT NULL,
 CONSTRAINT [PK_DOCTOR_SERVICE] PRIMARY KEY CLUSTERED 
(
	[DoctorServiceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[DOCTOR_SERVICE]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_SERVICE_DOCTOR] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[DOCTOR] ([DoctorID])
GO

ALTER TABLE [dbo].[DOCTOR_SERVICE] CHECK CONSTRAINT [FK_DOCTOR_SERVICE_DOCTOR]
GO

ALTER TABLE [dbo].[DOCTOR_SERVICE]  WITH CHECK ADD  CONSTRAINT [FK_DOCTOR_SERVICE_SERVICE] FOREIGN KEY([ServiceID])
REFERENCES [dbo].[SERVICE] ([ServiceID])
GO

ALTER TABLE [dbo].[DOCTOR_SERVICE] CHECK CONSTRAINT [FK_DOCTOR_SERVICE_SERVICE]
GO


