USE [CLINICS]
GO

/****** Object:  Table [dbo].[REGISTRATION_TIME]    Script Date: 14.05.2022 19:27:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGISTRATION_TIME](
	[TimeID] [int] identity(1,1) NOT NULL,
	[Time] [time](7) NULL,
 CONSTRAINT [PK_REGISTRATION_TIME] PRIMARY KEY CLUSTERED 
(
	[TimeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


