USE [CLINICS]
GO

/****** Object:  Table [dbo].[REGISTRATION]    Script Date: 14.05.2022 19:23:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGISTRATION](
	[RegistationID] [int] NOT NULL identity(1,1),
	[ClientID] [int] NOT NULL,
	[DoctorServiceID] [int] NOT NULL,
	[DateID] [int] NOT NULL,
	[Status] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_REGISTRATION] PRIMARY KEY CLUSTERED 
(
	[RegistationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRATION_CLIENT] FOREIGN KEY([ClientID])
REFERENCES [dbo].[CLIENT] ([ClientID])
GO

ALTER TABLE [dbo].[REGISTRATION] CHECK CONSTRAINT [FK_REGISTRATION_CLIENT]
GO

ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRATION_DOCTOR_SERVICE] FOREIGN KEY([DoctorServiceID])
REFERENCES [dbo].[DOCTOR_SERVICE] ([DoctorServiceID])
GO

ALTER TABLE [dbo].[REGISTRATION] CHECK CONSTRAINT [FK_REGISTRATION_DOCTOR_SERVICE]
GO

ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRATION_REGISTRATION_DATE] FOREIGN KEY([DateID])
REFERENCES [dbo].[REGISTRATION_DATE] ([DateID])
GO

ALTER TABLE [dbo].[REGISTRATION] CHECK CONSTRAINT [FK_REGISTRATION_REGISTRATION_DATE]
GO


