//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLINICS.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR_RATING
    {
        public int CommentID { get; set; }
        public int DoctorID { get; set; }
        public int ClientID { get; set; }
        public double Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
