//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLINICS.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR_SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR_SERVICE()
        {
            this.REGISTRATIONs = new HashSet<REGISTRATION>();
        }
    
        public int DoctorServiceID { get; set; }
        public int DoctorID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRATION> REGISTRATIONs { get; set; }
    }
}
