//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLINICS.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLINICSEntities : DbContext
    {
        private static CLINICSEntities context;

        public static CLINICSEntities GetContext()
        {
            if (context == null)
                context = new CLINICSEntities();
            return context;
        }

        public CLINICSEntities()
            : base("name=CLINICSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<DOCTOR_RATING> DOCTOR_RATING { get; set; }
        public virtual DbSet<DOCTOR_SERVICE> DOCTOR_SERVICE { get; set; }
        public virtual DbSet<REGISTRATION> REGISTRATIONs { get; set; }
        public virtual DbSet<REGISTRATION_DATE> REGISTRATION_DATE { get; set; }
        public virtual DbSet<REGISTRATION_TIME> REGISTRATION_TIME { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
