//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLINICS.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION_TIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRATION_TIME()
        {
            this.REGISTRATION_DATE = new HashSet<REGISTRATION_DATE>();
        }
    
        public int TimeID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRATION_DATE> REGISTRATION_DATE { get; set; }
    }
}
