//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLINICS.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        public int RegistationID { get; set; }
        public int ClientID { get; set; }
        public int DoctorServiceID { get; set; }
        public int DateID { get; set; }
        public string Status { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual DOCTOR_SERVICE DOCTOR_SERVICE { get; set; }
        public virtual REGISTRATION_DATE REGISTRATION_DATE { get; set; }
    }
}
